---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность зарегистрироваться с помощью аккаунта в GitHub
  - Пользователь должен иметь возможность зарегистрироваться с помощью аккаунта в Discord
  - Зарегистрированный пользователь получает доступ к чату, он может отправлять сообщения, читать сообщения других пользователей, видеть отправителя сообщения
  - На главной странице отображается рейтинг игроков и последние игры
  - В редакторе пользователь должен иметь возможность выбрать язык
  - В редакторе пользователь должен иметь возможность редактировать синтаксис выбранного языка
  - В редакторе при нажатии на кнопку "RUN" должен проверяться написанный код
  - Во время игры экран должен быть разделен на две области, игрок должен видеть и свои действия, и действия соперника
  - Для игры можно выбрать одного из зарегестрированных пользователей сайта
  - Для игры можно выбрать бота
  - Для игры можно пригласить стороннего пользователя с помощью ссылки
  - Во время игры игрок видит свое имя и имя соперника
  - При неправильности кода игрок должен получать ошибку, после того, как код был проверен тестами
  - У игрока должна быть возможность сдаться с помощью соответствующей кнопки
  - При выигрыше появляется всплывающее окно с оповещением
  - После результатов проверки должно появляться всплывающее окно
  - Добавленные используемые языки должны содержать несколько версий
  - Игрок должен видеть статус игры
  - При наведении курса на имя игрока, должна высвечиваться информация о нем
  - При нажатии на имя другого игрока, должно происходить перемещение на страницу его профиля
  - На главной странице сайта расположены чат, рейтинг игроков, кнопка 'Create a game', таблицы Lobby, информация о турнирах, история
  - У пользователь должна быть возможность переключаться между General и Notifications, и видеть информацию каждого раздела
  - При нажатии на кнопку 'Create a game' должно появляться меню выбора условий игры
  - Рейтинг игроков возможно просмотреть за неделю, месяц, либо за все время
  - Можно увидеть топ-лист игроков с помощью сслыки Top list
  - Во вкладке Lobby должны отображаться уровень, статус игры, игроки и возможные действия
  - При нажатии на кнопку 'Fight' в графе действия, должна начинаться игра
  - Во вкладке Tournaments должны отображаться название, тип, время начала турнира и возможные действия
  - При нажатии на кнопку 'Show' в графе действий, пользователь должен иметь возможность просмотреть информацию о турнире
  - Во вкладке History должен отображаться списко завершенных игр игрока
  - Если игрок еще не завершил ни одной игры, должно отображаться сообщение 'No completed games'
  - Игрок должен свободно переключаться между вкладками Lobby, Tournaments, History на главном экране. При переключении , на странице постоянно отображаются чат, рейтинг и кнопка ' Create a game'
  - Пользователь должен видеть количество пользователей online
  - Пользователь должен иметь возможность оценить сайт, перейдя по ссылке на GitHub
  - Пользователь должен иметь возможность вызвать другого игрока на бой
  - Пользователь должен видеть вызовы на бой от других игроков
  - При нажатии на собственное имя на главном экране, пользователь получает доступ к выпадающему списку (Мой профиль, настройки, рейтинг пользователей, кланы, ссылки на SourceCode, Hexlet, discord Telegram для присоединения к сообществам), кнопку выхода
  - В профиле игрока во вкладке Statistics должна содержаться информация о ранге, силе игрока и количестве игр
  - В профиле игрока во вкладке Completed games должна содержаться информация о завершенных играх
  - В разделе настроек игрок может редактировать имя
  - В разделе настроек игрок может выбрать оружие
  - В разделе настроек игрок может написать название клана (не обязательно)
  - В разделе настроек игрок может выбрать звуковое уведомление 
  - В разделе настроек игрок может изменить уровень громкости звукового уведомления
  - В разделе настроек игро должен иметь возможность настроить ссылки на GitHub и/или Discord
  - В разделе рейтинга игроков отображается имя игрока, ранг, рейтинг, количество проведенных игр, время присоединения к сайту, ссылка на GitHub
  - В разделе рейтинга игроков можно осуществлять поиск игроков по имени игрока
  - В разделе рейтинга игроков можно выставлять фильтрацию по количеству игроков на странице
  - В раздеде рейтинга игроков можно просматривать ботов с помощью активации чек-бокса With bots
  - В разделе рейтинга игроков можно просматривать информацию за неделю, месяц или за все время
  - В разделе рейтинга игроков можно настраивать фильтрацию отображения информации о ранке, рейтинге, количеству проведенных игр и времени регистрации в убывающем или в возрастающем порядке
  - В разделе заданий пользователь видит список заданий и следующую информацию о каждом, как id, название, уровень, тэги, источник, статус, видимость, время последнего обновления и действия с заданием
  - В разделе задания при нажатии на кнопку 'Show' должен отображаться редактор с информацией задания
  - Во вкладке кланы должно отображаться имя клана, полное имя (не обязательно), создатель и возможные действия 
  - Во вкладке кланы при нажатии на кнопку 'Show' должно происходить перенаправление на страницу клана с информацией о создателе, игроках, времени создания клана, и времени присоединения игроков к клану
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Незарегистрированный пользователь не может просмотреть содержимое сайта
  - Незарегистрированный пользователь не может начать игру
  - Игроки не могут участвовать в двух играх одновременно
  - Игроки не могут удалять сообщения других игроков в чате
  - Игроки не могут писать код на языках, которых нет в редакторе
  - Игроки не могут изменять информацию и рейтинг других игроков
  - Тестирование кода должно проходить без ошибок
  - Игрок должен иметь возможность обратиться в поддержку при возникновении ошибок со стороны программы
  - Игрок должен иметь возможность связаться с разработчиками игры, чтобы предложить улучшения и/или исправления
  - Задание должно быть решаемым
